FROM node:20


RUN npm install -g pnpm

WORKDIR /app


COPY package.json pnpm-lock.yaml pnpm-workspace.yaml turbo.json ./
COPY .npmrc .npmrc


COPY apps ./apps
COPY packages ./packages


RUN pnpm install --frozen-lockfile


RUN cd apps/web && pnpm add next

WORKDIR /app/apps/web

RUN mkdir -p /app/apps/web/node_modules/next && cp -r /app/node_modules/next/* /app/apps/web/node_modules/next/

CMD ["pnpm", "exec", "next", "dev", "--turbo", "--port", "3000"]
