services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - "5001:5001"
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/biocad
      REDIS_URL: redis://redis:6379
      PORT: 5001
    depends_on:
      - postgres
      - redis
    # volumes:
    #   - ./apps:/app/apps
    #   - ./packages:/app/packages
    working_dir: /app/apps/api

  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_API_URL: http://api:5001
    depends_on:
      - api
    working_dir: /app/apps/web

  postgres:
    image: postgres:15
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: biocad
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    restart: always
    ports:
      - "6379:6379"

volumes:
  pgdata:
