FROM node:20

RUN npm install -g pnpm

WORKDIR /app

COPY package.json pnpm-lock.yaml pnpm-workspace.yaml turbo.json ./
COPY .npmrc .npmrc

COPY apps ./apps
COPY packages ./packages


RUN pnpm install --frozen-lockfile

RUN npx prisma generate --schema=apps/api/prisma/schema.prisma


RUN mkdir -p /app/apps/api/node_modules/@nestjs/cli && cp -r /app/node_modules/@nestjs/cli/* /app/apps/api/node_modules/@nestjs/cli/

WORKDIR /app/apps/api

CMD ["pnpm", "exec", "nest", "start", "--watch"]
